language: c
compiler: gcc

install:
  - wget https://sourceforge.net/projects/ltp/files/Coverage%20Analysis/LCOV-1.14/lcov-1.14.tar.gz
  - gem install coveralls-lcov
  - gcc --version

before_script:
  - gunzip lcov-1.14.tar.gz
  - tar xvf lcov-1.14.tar
  - cd lcov-1.14; sudo make install; cd ..
  - lcov --version
  - lcov --directory . --zerocounters

script:
  - cmake .
  - cmake --build .

after_success:
  - lcov --capture --base-directory . --directory . --output-file coverage.info # capture coverage info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter out system, test, and external code
  - lcov --list coverage.info # debug before upload
  - coveralls-lcov coverage.info # uploads to coveralls
  - bash <(curl -s https://codecov.io/bash)
