version: 1.0.0.{build}

image: Visual Studio 2022
platform:
  - x64

build_script:
  - call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"
  - cmake .
  - cmake --build .
