version: 1.0.0.{build}

image: Visual Studio 2022
platform:
  - x64

environment:
  BDWGC_VERSION: 8.0.4
  BDWGC_ARCHIVE: gc-%BDWGC_VERSION%.tar.gz

install:
  # install BDWGC
  - if not exist %BDWGC_ARCHIVE% appveyor DownloadFile "https://github.com/ivmai/bdwgc/releases/download/v%BDWGC_VERSION%/%BDWGC_ARCHIVE%"
  - tar xf %BDWGC_ARCHIVE%
  - move gc-%BDWGC_VERSION% bdwgc

build_script:
  - call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"
  - cmake .
  - cmake --build .
