/*
    module  : mktime.c
    version : 1.4
    date    : 08/13/23
*/
#ifndef MKTIME_C
#define MKTIME_C

#include "decode.h"

/**
OK 1720  mktime  :  T  ->  I
Converts a list T representing local time into a time I.
T is in the format generated by localtime.
*/
PRIVATE void mktime_(pEnv env)
{
    struct tm t;

    ONEPARAM("mktime");
    LIST("mktime");
    decode_time(env, &t);
    UNARY(INTEGER_NEWNODE, (int64_t)mktime(&t));
}
#endif
